language: python
python:
  - 3.5
  - 3.6
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py develop

script:
  - make cov
  - python setup.py check -rms


after_success:

  - codecov

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "eCDk6LIug3AJJb7vyStX2JQ9/xG8RK4AP5SNyVGHTn+g59OxixYMdGRSTpeduWLQp/Xq2TZHGgnzIuo29Ir/stj+TorVmloZpk/Xt+Lm31u5IKeEytq2iditz+83iUvodXDyKADqOX8op5ARYyA+W2leYxzC6+q43O4GaXJOJeY="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6
